### PR TITLE
High-res textures and some more plants

### PR DESCRIPTION
**Pull request by ghost**
These are the optional textures to match the hdx and other high-res packs and the above-ground mushrooms.

### CODE REVIEW

**Comment by gaelysam** [comment]
"Gael-de-Sailly was the one who approved the pull request" : I've merged it quickely last week, without taking a look to the high-resolution textures.
That's very good but that's not the good place for them. You should propose it to @VanessaE. It's a WIP so that's not sure that it would be merged.

**Comment by VanessaE** [comment]
I'm open to pull requests for HDX, as long as the textures are 512px and good quality.  That said, when someone sends me a texture to use, I much prefer getting my hands on the original photos/renderings so that I can process them myself.

**Comment by VanessaE** [comment]
HDX has since been updated to support this package, at least partly.

**Comment by gaelysam** [comment]
thank you :)

**Pull request merged**
