### PR TITLE
Plants API

### PR DESCRIPTION
**Pull request by gaelysam**
The Plants API makes possible for external mods to generate plants in VMG worlds.

Since that's a heavy rewrite, we must all agree before merging.
About performance: I've hesitated to make it because it could be slower. In fact it seems not to be the case, or not too much (a few milliseconds) but it needs more tests.

I've a little changed the plants parameters (for example I've made the Bird of Paradise extremely rare)

And the API description in README.md ? Is that humanly readable and understandable ?
I need your opinion :)

### CODE REVIEW

**Comment by vlapsley** [comment]
Great work!
Plant distribution looks good. I'm happy to see that jungles are still dense and following a river under the dark cover of a jungle is a great feature I haven't seen in another mapgen.
I'll review the documentation and see how easy (or hard) it is to add a new plant - willow tree. I'll get on to this in the next 12 hours.

**Comment by ghost** [comment]
The api seems to be working perfectly, and it makes the code easier to read. There's no significant performance penalty on my system. In fact the test times have been unusually close. It seems to use less memory than schematic-based decorations.

It's a fairly complex function, but that's because of all the options available. It wasn't any simpler to plug plants in the old way, and it was easier to screw things up. I recommend merging it.

**Comment by vlapsley** [comment]
I have a commit based on this ready to go for the addition of a willow tree.

I can see no discernible difference in mapgen performance on my ancient laptop. I also recommend merging.

**Comment by gaelysam** [comment]
Ok so, merging.

**Pull request merged**
