### PR TITLE
Slimmer Trees

### PR DESCRIPTION
**Pull request by ghost**
I think the cherry tree and banana plant look a little beefier than real
life. This will make them slimmer. It might be appropriate for birch and willow trees too, but see what you think.

### CODE REVIEW

**Comment by vlapsley** [comment]
I like the concept.
Would it be better to have another column to the treelist array for _trunksize_?
So for arguments sake that the trunksize for banana tree is approx 75%, cherry blossoms and birch 50%

**Comment by ghost** [comment]
That would probably work better.

**Comment by ghost** [comment]
Ok, try that on for size.

**Comment by vlapsley** [comment]
Looks fantastic!

**Pull request merged**
