### PR TITLE
Add mangrove tree and fern.

### PR DESCRIPTION
**Pull request by vlapsley**
Ok, this needs some review.

I've changed "normal" trees to only appear above y=2. This stops them spawning on the edge of the water on the beach. Minor change but a little more realistic.

I've added a mangrove tree and fern where rivers meet the sea water. The mangrove tree has a roots node which is based on the jungle roots function. The roots node is "plantlike" and needs some improvement. I'm trying to keep the texture 16x16 and it looks a little clumsy.

It would be great if the roots angled inward to the tree trunk. I'm not sure how to achieve this.

Also, the roots sometimes go below water level and look a little ugly. It would be better if they were part of the water, rather than replacing it. The only mod I've seen do this is the "Sea" mod, but the code in it to remove "airblocks" is pretty big. On other occasions it will dig out dirt to make the roots. Adding water in there with the roots may look better to create a mangrove/marsh effect.  

Thoughts?

screenshot_20151030_213938

### CODE REVIEW

**Comment by gaelysam** [comment]
Mangrove should be in the water (when it's 1-2 blocks deep). That's not possible for now with Plants API but I think it's not very difficult to implement this.

About humidity parameter: keep in mind that it could (rarely) be very, very high, sometimes above 10. For the mangrove that grows in **extremely** wet places, I think that 1.5 is not enough. I suggest at least 5. Some other plants should be reworked.

**Comment by gaelysam** [comment]
In fact we will correct it after, it works now. Merging.

You can rework the parameters of the plants if you want.

**Comment by gaelysam** [comment]
9be8720

**Comment by ghost** [comment]
Wikipedia shows mangroves growing in sand, just like they show up here, though putting them in the water as well wouldn't hurt. I don't know if the water bubble effect is even worth bothering with in this case. They're always clustered together, so the bubble isn't as jarring as when you see it around a single seaweed node. To me, the places where the earth is dug out by roots looks just as odd.

You can use the noairblocks mod to easily remove bubbles underwater, but anything that breaks the surface spoils the effect. You could make the roots part of the sand nodes underneath, but the effect is spoiled if the side of the sand block is exposed, so you can't plant them on slopes, and making roots more than one block high would be a problem.

The only thing that nags at me is the lack of connection to the trunk. I'm not sure it's possible to fix that without making the roots networks of node boxes. You could just replace the bottom piece of trunk with a root node, but it still looks a bit odd.

**Pull request closed without merging**
